name: whittlehurst
channels:
  - defaults
dependencies:
  - python=3.12
  - twine
  - bokeh
  - matplotlib
  - plotly
  - colorcet
  - pip
  - pip:
    - build
    - pathos
    - hurst
    - antropy
    - nolds
    - whittlehurst==1.4