name: whittlehurst
channels:
  - defaults
dependencies:
  - python=3.12
  - twine
  - wheel
  - tqdm
  - bokeh
  - matplotlib
  - plotly
  - colorcet
  - pip
  - pip:
    - setuptools
    - pathos
    - hurst
    - antropy
    - nolds
    - stochastic
    - whittlehurst==1.3