name: whittlehurst
channels:
  - defaults
dependencies:
  - python=3.12
  - twine
  - wheel
  - numpy
  - scipy
  - tqdm
  - bokeh
  - matplotlib
  - plotly
  - colorcet
  - pip
  - pip:
    - setuptools
    - pathos